spring:
  rabbitmq:
    host: localhost
    port: 15672
    password: guest
    username: guest
    alert_queue: alert_queue
    daily_queue: daily_queue
    error_queue: error_queue
    common_queue: common_monitoring